### ISSUE TITLE
Please, add key-did-resolver

### ISSUE THREAD

**Issue by ukstv** [iankressin/magic-metamask-ceramic#1]
Here:
<img width="745" alt="Screenshot 2021-12-11 at 16 26 52" src="https://user-images.githubusercontent.com/193527/145678349-0ee2ce81-468e-4888-8ea1-031d0bf30eef.png">

**Comment by iankressin** [comment]
Thanks!

That was fix at `fab646b5554509a3c3b9bc4812e08626c6ecd2ac`

@ukstv Could you please shed some light on the reason that we need both `3id-did-resolver` and `key-did-resolver`, so I can write a better doc for that?

**Comment by ukstv** [comment]
You could find multitude of did methods. Every did method turns `did:METHOD:IDENTIFIER` into a proper DID Document, so that we can understand (in interoperable fashion!) what cryptographic key is used for signing stream updates. On Ceramic network you could most often (my personal estimate 99.9999%) find streams authored (=signed) with did-key and 3id. Although, did-key is rare, it could be present, so it is better to be on a safe side.

**Comment by iankressin** [comment]
Awesome, thank you so much!

It was a crystal clear explanation, I'll be updating the docs in a few hours
